document.writeln("        <!-- Sidebar -->");
document.writeln("        <div id=\'sidebar\'>");
document.writeln("            <link rel=\'stylesheet\' href=\'assets/css/main.css\' />");
document.writeln("            <div class=\'inner\'>");
document.writeln("");
document.writeln("                <!-- Search -->");
document.writeln("                    <section id=\'search\' class=\'alt\'>");
document.writeln("                        <form method=\'post\' action=\'#\'>");
document.writeln("                            <input type=\'text\' name=\'query\' id=\'query\' placeholder=\'Search\' />");
document.writeln("                        </form>");
document.writeln("                    </section>");
document.writeln("");
document.writeln("                <!-- Menu -->");
document.writeln("                    <nav id=\'menu\'>");
document.writeln("                        <header class=\'major\'>");
document.writeln("                            <h2>导航</h2>");
document.writeln("                        </header>");
document.writeln("                        <ul>");
document.writeln("                            <li><a href=\'index.html\'>主页</a></li>");
document.writeln("                            <li><a href=\'pages/Python.html\'>Python</a></li>");
document.writeln("                            <!-- <li><a href=\'pages/深度学习.html\'>深度学习</a></li> -->");
document.writeln("                            <li>");
document.writeln("                                <span class=\'opener\'>深度学习</span>");
document.writeln("                                <ul>");
document.writeln("                                    <li><a href=\'#\'>神经网络</a></li>");
document.writeln("                                    <li><a href=\'#\'>优化器</a></li>");
document.writeln("                                    <li><a href=\'#\'>损失函数</a></li>");
document.writeln("                                    <li><a href=\'pages/学习策略.html\'>学习策略</a></li>");
document.writeln("                                </ul>");
document.writeln("                            </li>");
document.writeln("                            <!-- <li>");
document.writeln("                                <span class=\'opener\'>Submenu</span>");
document.writeln("                                <ul>");
document.writeln("                                    <li><a href=\'#\'>Lorem Dolor</a></li>");
document.writeln("                                    <li><a href=\'#\'>Ipsum Adipiscing</a></li>");
document.writeln("                                    <li><a href=\'#\'>Tempus Magna</a></li>");
document.writeln("                                    <li><a href=\'#\'>Feugiat Veroeros</a></li>");
document.writeln("                                </ul>");
document.writeln("                            </li>");
document.writeln("                            <li><a href=\'#\'>Etiam Dolore</a></li>");
document.writeln("                            <li><a href=\'#\'>Adipiscing</a></li>");
document.writeln("                            <li>");
document.writeln("                                <span class=\'opener\'>Another Submenu</span>");
document.writeln("                                <ul>");
document.writeln("                                    <li><a href=\'#\'>Lorem Dolor</a></li>");
document.writeln("                                    <li><a href=\'#\'>Ipsum Adipiscing</a></li>");
document.writeln("                                    <li><a href=\'#\'>Tempus Magna</a></li>");
document.writeln("                                    <li><a href=\'#\'>Feugiat Veroeros</a></li>");
document.writeln("                                </ul>");
document.writeln("                            </li>");
document.writeln("                            <li><a href=\'#\'>Maximus Erat</a></li>");
document.writeln("                            <li><a href=\'#\'>Sapien Mauris</a></li>");
document.writeln("                            <li><a href=\'#\'>Amet Lacinia</a></li> -->");
document.writeln("                        </ul>");
document.writeln("                    </nav>");
document.writeln("");
document.writeln("                <!-- Section -->");
document.writeln("                    <section>");
document.writeln("                        <header class=\'major\'>");
document.writeln("                            <h2>最新发布</h2>");
document.writeln("                        </header>");
document.writeln("                        <div class=\'mini-posts\'>");
document.writeln("                            <article>");
document.writeln("                                <a href=\'#\' class=\'image\'><img src=\'images/pic07.jpg\' alt=\'\' /></a>");
document.writeln("                                <p>梯度逆转的原理及应用</p>");
document.writeln("                            </article>");
document.writeln("                            <!-- <article>");
document.writeln("                                <a href=\'#\' class=\'image\'><img src=\'images/pic08.jpg\' alt=\'\' /></a>");
document.writeln("                                <p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore aliquam.</p>");
document.writeln("                            </article>");
document.writeln("                            <article>");
document.writeln("                                <a href=\'#\' class=\'image\'><img src=\'images/pic09.jpg\' alt=\'\' /></a>");
document.writeln("                                <p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore aliquam.</p>");
document.writeln("                            </article> -->");
document.writeln("                        </div>");
document.writeln("                        <ul class=\'actions\'>");
document.writeln("                            <li><a href=\'#\' class=\'button\'>More</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </section>");
document.writeln("");
document.writeln("                <!-- Section -->");
document.writeln("                    <section>");
document.writeln("                        <header class=\'major\'>");
document.writeln("                            <h2>Get in touch</h2>");
document.writeln("                        </header>");
document.writeln("                        <p>Sed varius enim lorem ullamcorper dolore aliquam aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin sed aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.</p>");
document.writeln("                        <ul class=\'contact\'>");
document.writeln("                            <li class=\'icon solid fa-envelope\'><a href=\'#\'>information@untitled.tld</a></li>");
document.writeln("                            <li class=\'icon solid fa-phone\'>(000) 000-0000</li>");
document.writeln("                            <li class=\'icon solid fa-home\'>1234 Somewhere Road #8254<br />");
document.writeln("                            Nashville, TN 00000-0000</li>");
document.writeln("                        </ul>");
document.writeln("                    </section>");
document.writeln("");
document.writeln("                <!-- Footer -->");
document.writeln("                    <footer id=\'footer\'>");
document.writeln("                        <p class=\'copyright\'>&copy; Untitled. All rights reserved. Demo Images: <a href=\'https://unsplash.com\'>Unsplash</a>. Design: <a href=\'https://html5up.net\'>HTML5 UP</a>.</p>");
document.writeln("                    </footer>");
document.writeln("");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        ");